USE assetmgmt;

CREATE TABLE IF NOT EXISTS nominees (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id      INT UNSIGNED NOT NULL,
  asset_id     INT UNSIGNED NOT NULL,
  name         VARCHAR(100) NOT NULL,
  relationship VARCHAR(50)  NOT NULL,
  percentage   DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  phone        VARCHAR(15),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
  FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
  INDEX idx_user  (user_id),
  INDEX idx_asset (asset_id)
) ENGINE=InnoDB;
