module.exports = async function routes(fastify) {
  fastify.register(require('./auth.routes'), { prefix: '/auth' })
  fastify.register(require('./dashboard.routes'), { prefix: '/dashboard' })
  fastify.register(require('./assets/bankAccounts.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/mutualFunds.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/stocks.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/gold.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/govtSchemes.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/loans.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/bonds.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/insurance.routes'), { prefix: '/assets' })
  fastify.register(require('./assets/realEstate.routes'), { prefix: '/assets' })
  fastify.register(require('./market.routes'), { prefix: '/market' })
  fastify.register(require('./goals.routes'), { prefix: '' })
  fastify.register(require('./imports'), { prefix: '/imports' })
  fastify.register(require('./tax.routes'), { prefix: '/tax' })
  fastify.register(require('./analytics.routes'), { prefix: '/analytics' })
  fastify.register(require('./alerts.routes'), { prefix: '/alerts' })
  fastify.register(require('./reports.routes'), { prefix: '/reports' })
  fastify.register(require('./nominees.routes'), { prefix: '/nominees' })
  fastify.register(require('./documents.routes'), { prefix: '/documents' })
}
